// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8GuhMdRkUsAJO5fwP4Nq8C42FAcA_aKg',
    appId: '1:24736190869:web:4204ea2249ecc45efc269c',
    messagingSenderId: '24736190869',
    projectId: 'social-7a899',
    authDomain: 'social-7a899.firebaseapp.com',
    storageBucket: 'social-7a899.appspot.com',
    measurementId: 'G-R2KE37K1VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmt5qc3eGsjuD6Z_5bPlhWk0dSxljo-k',
    appId: '1:24736190869:android:6e0dcf6f2b76fb99fc269c',
    messagingSenderId: '24736190869',
    projectId: 'social-7a899',
    storageBucket: 'social-7a899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwAYU23V4rdRJcNguRiNny7wJTuuURoc',
    appId: '1:24736190869:ios:bca88d2ce099dde6fc269c',
    messagingSenderId: '24736190869',
    projectId: 'social-7a899',
    storageBucket: 'social-7a899.appspot.com',
    iosClientId: '24736190869-7kvasv4767cbc6suh8hibasdhbr818s1.apps.googleusercontent.com',
    iosBundleId: 'com.social.media.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwAYU23V4rdRJcNguRiNny7wJTuuURoc',
    appId: '1:24736190869:ios:bca88d2ce099dde6fc269c',
    messagingSenderId: '24736190869',
    projectId: 'social-7a899',
    storageBucket: 'social-7a899.appspot.com',
    iosClientId: '24736190869-7kvasv4767cbc6suh8hibasdhbr818s1.apps.googleusercontent.com',
    iosBundleId: 'com.social.media.socialMedia',
  );
}
